#!/usr/bin/zsh

source "${0:h}/colors"

bspc config focused_border_color         "#$BLUE"
bspc config focused_locked_border_color  "#$CYAN"
bspc config focused_private_border_color "#$MAGENTA"
bspc config active_border_color          "#$WHITE"
bspc config active_locked_border_color   "#$WHITE"
bspc config active_private_border_color  "#$WHITE"
bspc config normal_border_color          "#$BLACK"
bspc config normal_locked_border_color   "#$BLACK"
bspc config normal_private_border_color  "#$BLACK"
bspc config presel_border_color          "#$ORANGE"
bspc config urgent_border_color          "#$RED"

bspc config gapless_monocle     true
bspc config borderless_monocle  true
bspc config auto_alternate      true
bspc config history_aware_focus true
bspc config auto_cancel         true

bspc config border_width 4
bspc config window_gap   6

bspc monitor -d $(seq 1 9)

bspc desktop ^1 -l monocle

if [[ -e "$BSPWM_TREE" ]]; then
	bspc restore -T "$BSPWM_TREE"
	rm "$BSPWM_TREE"
else
	bspc control --adopt-orphans
fi

if [[ -e "$BSPWM_HISTORY" ]]; then
	bspc restore -H "$BSPWM_HISTORY"
	rm "$BSPWM_HISTORY"
fi

if [[ -e "$BSPWM_STACK" ]]; then
	bspc restore -S "$BSPWM_STACK"
	rm "$BSPWM_STACK"
fi

bspc rule -a lxappearance floating=on
bspc rule -a xfontsel floating=on
bspc rule -a Steam floating=on
