alias sudo='sudo '
alias pacman='sudo pacman-color'
alias psmem='sudo ps_mem'
alias open='xdg-open'
alias extract='aunpack'
alias suspend-usb='sudo suspend-usb-device'

alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias update-fonts='fc-cache -fv'
alias ssh='eval "$(keychain --eval --agents ssh -Q --quiet ~/.ssh/id_rsa)" && ssh'
